export const ADMIN_ROUTE = '/admin'
export const ACCOUNT_ROUTE = '/account'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const CALCULATOR_ROUTE = '/calculator'
export const LOGIN_ADMIN_ROUTE = '/login/admin'